language: node_js
cache: yarn
notifications:
  email: false
node_js: '10'
install: yarn --frozen-lockfile
script: yarn validate
after_success:
  - npx codecov --disable=gcov
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && npx semantic-release
branches:
  only:
    - develop
    - master
